### ISSUE TITLE
Manually format Sensor Naming?

### ISSUE THREAD

**Issue by pixelwave** [LordBoos/discord_game#37]
Is there a way to manually add a prefix to each sensor created? Since all are in the format "sensor.username_1234" it is difficult for an autofill plugin to put all discord members in a card. Something like "sensor.discord_username_1234" would be great ...

**Comment by LordBoos** [comment]
fixed in https://github.com/LordBoos/discord_game/commit/1825cdbe769185cb266387e88f6366dce0b9dc2f

**Comment by pixelwave** [comment]
I checked - and also updated to 4.2.2. The config files also look like you describe in the fix. But the sensors still do not have the "discord_" prefix ... ?

**Comment by LordBoos** [comment]
It will only work for newly added sensors from this integration, because entity id is user configurable. If you want to update your existing entities, you have to remove discord_game, manualy delete all discord game entities and add discord_game back.

**Comment by pixelwave** [comment]
Thanks for the info - then I will reinstall and rewire the card ..

**Comment by LordBoos** [comment]
Please keep in mind, that you have to restart HA after you remove discord_game before removing the entities.

**Comment by pixelwave** [comment]
Worked - thanks!
